const grid = [
        {
            id: 1,
            up: 0,
            down: 16,
            left: 0,
            right: 0,
        },
        {
            id: 2,
            up: 0,
            down: 17,
            left: 0,
            right: 3,
        },
        {
            id: 3,
            up: 0,
            down: 18,
            left: 2,
            right: 4,
        },
        {
            id: 4,
            up: 0,
            down: 0,
            left: 3,
            right: 5,
        },
        {
            id: 5,
            up: 0,
            down: 0,
            left: 4,
            right: 6,
        },
        {
            id: 6,
            up: 0,
            down: 21,
            left: 5,
            right: 0,
        },
        {
            id: 7,
            up: 0,
            down: 22,
            left: 0,
            right: 8,
        },
        {
            id: 8,
            up: 0,
            down: 0,
            left: 7,
            right: 9,
        },
        {
            id: 9,
            up: 0,
            down: 24,
            left: 8,
            right: 0,
        },
        {
            id: 10,
            up: 0,
            down: 25,
            left: 0,
            right: 11,
        },
        {
            id: 11,
            up: 0,
            down: 0,
            left: 10,
            right: 12,
        },
        {
            id: 12,
            up: 0,
            down: 0,
            left: 11,
            right: 13,
        },
        {
            id: 13,
            up: 0,
            down: 0,
            left: 12,
            right: 14,
        },
        {
            id: 14,
            up: 0,
            down: 29,
            left: 13,
            right: 0,
        },
        {
            id: 15,
            up: 0,
            down: 30,
            left: 0,
            right: 0,
        },
        {
            id: 16,
            up: 1,
            down: 31,
            left: 0,
            right: 17,
        },
        {
            id: 17,
            up: 2,
            down: 0,
            left: 16,
            right: 0,
        },
        {
            id: 18,
            up: 3,
            down: 0,
            left: 0,
            right: 19,
        },
        {
            id: 19,
            up: 0,
            down: 34,
            left: 18,
            right: 0,
        },
        {
            id: 20,
            up: 0,
            down: 35,
            left: 0,
            right: 0,
        },
        {
            id: 21,
            up: 6,
            down: 36,
            left: 0,
            right: 0,
        },
        {
            id: 22,
            up: 7,
            down: 37,
            left: 0,
            right: 23,
        },
        {
            id: 23,
            up: 0,
            down: 38,
            left: 22,
            right: 0,
        },
        {
            id: 24,
            up: 9,
            down: 39,
            left: 0,
            right: 0,
        },
        {
            id: 25,
            up: 10,
            down: 0,
            left: 0,
            right: 26,
        },
        {
            id: 26,
            up: 0,
            down: 41,
            left: 25,
            right: 0,
        },
        {
            id: 27,
            up: 0,
            down: 42,
            left: 0,
            right: 28,
        },
        {
            id: 28,
            up: 0,
            down: 43,
            left: 27,
            right: 0,
        },
        {
            id: 29,
            up: 14,
            down: 44,
            left: 0,
            right: 0,
        },
        {
            id: 30,
            up: 15,
            down: 45,
            left: 0,
            right: 0,
        },
]

export default (grid)
