const grid = [
        {
            id: 1,
            up: 0,
            down: 16,
            left: 0,
            right: 0,
        },
        {
            id: 2,
            up: 0,
            down: 17,
            left: 0,
            right: 3,
        },
        {
            id: 3,
            up: 0,
            down: 18,
            left: 2,
            right: 4,
        },
        {
            id: 4,
            up: 0,
            down: 0,
            left: 3,
            right: 5,
        },
        {
            id: 5,
            up: 0,
            down: 0,
            left: 4,
            right: 6,
        },
        {
            id: 6,
            up: 0,
            down: 21,
            left: 5,
            right: 0,
        },
        {
            id: 7,
            up: 0,
            down: 22,
            left: 0,
            right: 8,
        },
        {
            id: 8,
            up: 0,
            down: 0,
            left: 7,
            right: 9,
        },
        {
            id: 9,
            up: 0,
            down: 24,
            left: 8,
            right: 0,
        },
        {
            id: 10,
            up: 0,
            down: 25,
            left: 0,
            right: 11,
        },
        {
            id: 11,
            up: 0,
            down: 0,
            left: 10,
            right: 12,
        },
        {
            id: 12,
            up: 0,
            down: 0,
            left: 11,
            right: 13,
        },
        {
            id: 13,
            up: 0,
            down: 0,
            left: 12,
            right: 14,
        },
        {
            id: 14,
            up: 0,
            down: 29,
            left: 13,
            right: 0,
        },
        {
            id: 15,
            up: 0,
            down: 30,
            left: 0,
            right: 0,
        },
        {
            id: 16,
            up: 1,
            down: 31,
            left: 0,
            right: 17,
        },
        {
            id: 17,
            up: 2,
            down: 0,
            left: 16,
            right: 0,
        },
        {
            id: 18,
            up: 3,
            down: 0,
            left: 0,
            right: 19,
        },
        {
            id: 19,
            up: 0,
            down: 34,
            left: 18,
            right: 0,
        },
        {
            id: 20,
            up: 0,
            down: 35,
            left: 0,
            right: 0,
        },
        {
            id: 21,
            up: 6,
            down: 36,
            left: 0,
            right: 0,
        },
        {
            id: 22,
            up: 7,
            down: 37,
            left: 0,
            right: 23,
        },
        {
            id: 23,
            up: 0,
            down: 38,
            left: 22,
            right: 0,
        },
        {
            id: 24,
            up: 9,
            down: 39,
            left: 0,
            right: 0,
        },
        {
            id: 25,
            up: 10,
            down: 0,
            left: 0,
            right: 26,
        },
        {
            id: 26,
            up: 0,
            down: 41,
            left: 25,
            right: 0,
        },
        {
            id: 27,
            up: 0,
            down: 42,
            left: 0,
            right: 28,
        },
        {
            id: 28,
            up: 0,
            down: 43,
            left: 27,
            right: 0,
        },
        {
            id: 29,
            up: 14,
            down: 44,
            left: 0,
            right: 0,
        },
        {
            id: 30,
            up: 15,
            down: 45,
            left: 0,
            right: 0,
        },
        {
            id: 31,
            up: 16,
            down: 46,
            left: 0,
            right: 0,
        },
        {
            id: 32,
            up: 0,
            down: 47,
            left: 0,
            right: 0,
        },
        {
            id: 33,
            up: 0,
            down: 48,
            left: 0,
            right: 34,
        },
        {
            id: 34,
            up: 19,
            down: 0,
            left: 33,
            right: 0,
        },
        {
            id: 35,
            up: 20,
            down: 0,
            left: 0,
            right: 36,
        },
        {
            id: 36,
            up: 21,
            down: 0,
            left: 35,
            right: 0,
        },
        {
            id: 37,
            up: 22,
            down: 0,
            left: 0,
            right: 0,
        },
        {
            id: 38,
            up: 23,
            down: 53,
            left: 0,
            right: 0,
        },
        {
            id: 39,
            up: 24,
            down: 0,
            left: 0,
            right: 40,
        },
        {
            id: 40,
            up: 0,
            down: 0,
            left: 39,
            right: 41,
        },
        {
            id: 41,
            up: 26,
            down: 0,
            left: 40,
            right: 0,
        },
        {
            id: 42,
            up: 27,
            down: 57,
            left: 0,
            right: 0,
        },
        {
            id: 43,
            up: 28,
            down: 58,
            left: 0,
            right: 0,
        },
        {
            id: 44,
            up: 29,
            down: 0,
            left: 0,
            right: 45,
        },
        {
            id: 45,
            up: 30,
            down: 0,
            left: 44,
            right: 0,
        },
        {
            id: 46,
            up: 31,
            down: 61,
            left: 0,
            right: 0,
        },
        {
            id: 47,
            up: 32,
            down: 62,
            left: 0,
            right: 0,
        },
        {
            id: 48,
            up: 33,
            down: 63,
            left: 0,
            right: 0,
        },
        {
            id: 49,
            up: 0,
            down: 0,
            left: 0,
            right: 50,
        },
        {
            id: 50,
            up: 0,
            down: 0,
            left: 49,
            right: 51,
        },
        {
            id: 51,
            up: 0,
            down: 0,
            left: 50,
            right: 52,
        },
        {
            id: 52,
            up: 0,
            down: 67,
            left: 51,
            right: 0,
        },
        {
            id: 53,
            up: 38,
            down: 68,
            left: 0,
            right: 0,
        },
        {
            id: 54,
            up: 0,
            down: 0,
            left: 0,
            right: 55,
        },
        {
            id: 55,
            up: 0,
            down: 70,
            left: 54,
            right: 56,
        },
        {
            id: 56,
            up: 0,
            down: 0,
            left: 55,
            right: 57,
        },
        {
            id: 57,
            up: 42,
            down: 0,
            left: 56,
            right: 0,
        },
        {
            id: 58,
            up: 43,
            down: 0,
            left: 0,
            right: 59,
        },
        {
            id: 59,
            up: 0,
            down: 0,
            left: 58,
            right: 60,
        },
        {
            id: 60,
            up: 0,
            down: 0,
            left: 59,
            right: 0,
        },
        {
            id: 181,
            up: 166,
            down: 196,
            left: 0,
            right: 0,
        },
        {
            id: 182,
            up: 167,
            down: 197,
            left: 0,
            right: 0,
        },
        {
            id: 183,
            up: 168,
            down: 198,
            left: 0,
            right: 184,
        },
        {
            id: 184,
            up: 169,
            down: 0,
            left: 183,
            right: 0,
        },
        {
            id: 185,
            up: 170,
            down: 200,
            left: 0,
            right: 0,
        },
        {
            id: 186,
            up: 171,
            down: 0,
            left: 0,
            right: 187,
        },
        {
            id: 187,
            up: 172,
            down: 0,
            left: 186,
            right: 0,
        },
        {
            id: 188,
            up: 173,
            down: 203,
            left: 0,
            right: 0,
        },
        {
            id: 189,
            up: 174,
            down: 204,
            left: 0,
            right: 0,
        },
        {
            id: 190,
            up: 0,
            down: 205,
            left: 0,
            right: 191,
        },
        {
            id: 191,
            up: 176,
            down: 206,
            left: 190,
            right: 0,
        },
        {
            id: 192,
            up: 177,
            down: 207,
            left: 0,
            right: 0,
        },
        {
            id: 193,
            up: 178,
            down: 208,
            left: 0,
            right: 0,
        },
        {
            id: 166,
            up: 151,
            down: 181,
            left: 0,
            right: 0,
        },
        {
            id: 167,
            up: 152,
            down: 182,
            left: 0,
            right: 0,
        },
        {
            id: 168,
            up: 153,
            down: 183,
            left: 0,
            right: 0,
        },
        {
            id: 169,
            up: 0,
            down: 184,
            left: 0,
            right: 170,
        },
        {
            id: 170,
            up: 0,
            down: 185,
            left: 169,
            right: 0,
        },
        {
            id: 171,
            up: 156,
            down: 186,
            left: 0,
            right: 0,
        },
        {
            id: 172,
            up: 0,
            down: 187,
            left: 0,
            right: 173,
        },
        {
            id: 173,
            up: 0,
            down: 188,
            left: 172,
            right: 0,
        },
        {
            id: 174,
            up: 0,
            down: 189,
            left: 0,
            right: 175,
        },
        {
            id: 175,
            up: 0,
            down: 0,
            left: 174,
            right: 176,
        },
        {
            id: 176,
            up: 0,
            down: 191,
            left: 175,
            right: 177,
        },
        {
            id: 177,
            up: 0,
            down: 192,
            left: 176,
            right: 0,
        },
        {
            id: 178,
            up: 0,
            down: 193,
            left: 0,
            right: 179,
        },
        {
            id: 179,
            up: 0,
            down: 194,
            left: 178,
            right: 180,
        },
        {
            id: 180,
            up: 0,
            down: 195,
            left: 179,
            right: 0,
        },
        {
            id: 194,
            up: 179,
            down: 0,
            left: 0,
            right: 0,
        },
        {
            id: 195,
            up: 180,
            down: 0,
            left: 0,
            right: 0,
        },
        {
            id: 196,
            up: 181,
            down: 0,
            left: 0,
            right: 197,
        },
        {
            id: 197,
            up: 182,
            down: 0,
            left: 196,
            right: 0,
        },
        {
            id: 198,
            up: 183,
            down: 0,
            left: 0,
            right: 199,
        },
        {
            id: 199,
            up: 0,
            down: 214,
            left: 198,
            right: 0,
        },
        {
            id: 200,
            up: 185,
            down: 0,
            left: 0,
            right: 201,
        },
        {
            id: 201,
            up: 0,
            down: 0,
            left: 200,
            right: 202,
        },
        {
            id: 202,
            up: 0,
            down: 0,
            left: 201,
            right: 203,
        },
        {
            id: 203,
            up: 188,
            down: 0,
            left: 202,
            right: 0,
        },
        {
            id: 204,
            up: 189,
            down: 219,
            left: 0,
            right: 0,
        },
        {
            id: 205,
            up: 190,
            down: 220,
            left: 0,
            right: 0,
        },
        {
            id: 206,
            up: 191,
            down: 0,
            left: 207,
            right: 0,
        },
        {
            id: 207,
            up: 192,
            down: 0,
            left: 206,
            right: 0,
        },
        {
            id: 208,
            up: 193,
            down: 0,
            left: 0,
            right: 209,
        },
        {
            id: 209,
            up: 0,
            down: 0,
            left: 208,
            right: 210,
        },
        {
            id: 210,
            up: 0,
            down: 225,
            left: 209,
            right: 0,
        },
        {
            id: 211,
            up: 0,
            down: 0,
            left: 0,
            right: 212,
        },
        {
            id: 212,
            up: 0,
            down: 0,
            left: 211,
            right: 213,
        },
        {
            id: 213,
            up: 0,
            down: 0,
            left: 212,
            right: 0,
        },
        {
            id: 214,
            up: 199,
            down: 0,
            left: 0,
            right: 215,
        },
        {
            id: 215,
            up: 0,
            down: 0,
            left: 214,
            right: 216,
        },
        {
            id: 216,
            up: 0,
            down: 0,
            left: 215,
            right: 217,
        },
        {
            id: 217,
            up: 0,
            down: 0,
            left: 216,
            right: 218,
        },
        {
            id: 218,
            up: 0,
            down: 0,
            left: 217,
            right: 219,
        },
        {
            id: 219,
            up: 204,
            down: 0,
            left: 218,
            right: 0,
        },
        {
            id: 220,
            up: 205,
            down: 0,
            left: 0,
            right: 221,
        },
        {
            id: 221,
            up: 0,
            down: 0,
            left: 220,
            right: 222,
        },
        {
            id: 222,
            up: 0,
            down: 0,
            left: 221,
            right: 223,
        },
        {
            id: 223,
            up: 0,
            down: 0,
            left: 222,
            right: 0,
        },
        {
            id: 224,
            up: 0,
            down: 0,
            left: 0,
            right: 225,
        },
        {
            id: 225,
            up: 210,
            down: 0,
            left: 224,
            right: 0,
        },
]

export default (grid)
